[package]
name = "todo-tutorial"
version = "0.1.0"
edition = "2024"

[dependencies]
druid = { version = "0.8.3", features = ["im"] }
im = "15.0.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
directories = "6.0.0"